version: '3.8'

networks:
  internet:
    name: internet
  local:
    name: local

services:
  php-fpm:
    image: php:8.2.13-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - .:/app
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo pdo_mysql && php-fpm"
    networks:
      - local

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mysql
    networks:
      - internet
      - local

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "1500:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - internet
      - local
