version: '3.8'

networks:
  internet:
    name: internet
  # Настраиваем сеть. Теперь у локального хоста всегда будет один и тот же IP - 192.168.220.1
  local:
    name: local
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  php-fpm:
    image: php:8.2.13-fpm
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /app
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
    volumes:
      - .:/app
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && pecl install xdebug-3.2.2 && docker-php-ext-enable pdo pdo_mysql xdebug && php-fpm"
    networks:
      - local

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mysql
    networks:
      - internet
      - local

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - local
